Feature/doc updates
fivetran/dbt_salesforce pull request #28
Opened 2022-04-29 22:57 UTC by fivetran-reneeli

Pull Request
**Are you a current Fivetran customer?** 

Internal
**What change(s) does this PR introduce?** 

- Updating package structure to align with most recent standards 
**Did you update the CHANGELOG?** 

- [x] Yes

**Does this PR introduce a breaking change?**

- [ ] Yes (please provide breaking change details below.)
- [x] No  (please provide an explanation as to how the change is non-breaking below.)
No, but lots of updates to warrant a refresh
**Did you update the dbt_project.yml files with the version upgrade (please leverage standard semantic versioning)? (In both your main project and integration_tests)** 

- [x] Yes

**Is this PR in response to a previously created Bug or Feature Request**

- [ ] Yes, Issue/Feature [link bug/feature number here]
- [x] No 

**How did you test the PR changes?** 

 

- [x] CircleCi  
- [x] Local (please provide additional testing details below)

**Select which warehouse(s) were used to test the PR**
 

- [x] BigQuery
- [x] Redshift
- [x] Snowflake
- [x] Postgres
- [x] Databricks
- [ ] Other (provide details below)

**Provide an emoji that best describes your current mood**
 
:dancer:

**Feedback**

We are so excited you decided to contribute to the Fivetran community dbt package! We continue to work to improve the packages and would greatly appreciate your [feedback](https://www.surveymonkey.com/r/DQ7K7WW) on our existing dbt packages or what you'd like to see next.

2022-05-02 18:33 UTC, fivetran-reneeli commented on README v2.md
> +# Salesforce Modeling dbt Package ([Docs](https://fivetran.github.io/dbt_salesforce/))
I noticed salesforce used the old netlify link-- updated it.

2022-05-03 15:18 UTC, fivetran-joemarkiewicz requested changes
@fivetran-reneeli thanks for these updates! I have a few questions and requests to change in my comments below. Let me know if you have any questions 😄

2022-05-03 15:18 UTC, fivetran-joemarkiewicz commented on models/salesforce__manager_performance.sql
> +              else 0 end, 2) as total_win_percent
Can we line the `end` statements with the `round(case` statements? See [here](https://github.com/fivetran/dbt_style_guide/blob/main/sql_guidelines.md) for an example.

2022-05-03 15:18 UTC, fivetran-joemarkiewicz commented on models/salesforce__opportunity_enhanced.sql
> +        {{ var('opportunity_enhanced_pass_through_columns') | join (", ")}}
Can you update this to be explicit and in line with our new standards
```suggestion
        {% if var('opportunity_enhanced_pass_through_columns',[]) != [] %}
        , {{ var('opportunity_enhanced_pass_through_columns') | join (", ")}}
```

2022-05-03 15:18 UTC, fivetran-joemarkiewicz commented on models/salesforce__owner_performance.sql
>  from opportunity_aggregation_by_owner
`from` should be flush with the last select statement above?

2022-05-03 15:18 UTC, fivetran-joemarkiewicz commented on packages.yml
> +      warn-unpinned: false
Obligatory reminder to switch before merge

2022-05-03 15:18 UTC, fivetran-joemarkiewicz commented on models/salesforce__owner_performance.sql
> +    end as total_win_percent
Only comment on these is that the `then` should be on the same line as it's clause.
```sql
    case 
        when (total_bookings_amount + total_lost_amount) > 0 
            then total_bookings_amount / (total_bookings_amount + total_lost_amount) * 100
        else 0 
    end as total_win_percent
```

2022-05-03 23:28 UTC, fivetran-reneeli commented on models/salesforce__manager_performance.sql
> +user_role as (
That's a good point. I tried moving `user` cte to be the last, but then that would've messed up the commas in the compiled version, which goes against what we're trying to do with our formatting updates, so I'll do this instead

2022-05-05 20:55 UTC, fivetran-joemarkiewicz approved these changes
Looks good! I just have a few requests to edit the README a bit. Once those changes are applied you are good to merge to the release branch!

2022-05-05 20:55 UTC, fivetran-joemarkiewicz commented on CHANGELOG.md
> +- Updating package structure to align with most recent standards
Can you add more context here. Similar to what you did within the source pacakge.

2022-05-05 20:55 UTC, fivetran-joemarkiewicz commented on README.md
> +- **Database support**: This package has been tested on **BigQuery**, **Snowflake**, **Redshift**, **Spark**, and **Postgres**. Ensure you are using one of these supported databases.
```suggestion
- **Database support**: This package has been tested on **BigQuery**, **Snowflake**, **Redshift**, **Databricks**, and **Postgres**. Ensure you are using one of these supported databases.
```

2022-05-05 20:55 UTC, fivetran-joemarkiewicz commented on README.md
>  This package allows users to add additional columns to the opportunity enhanced table. Columns passed through must be present in the downstream source account table or user table. If you want to incl
Can you add a header to this section

2022-05-05 20:55 UTC, fivetran-joemarkiewicz commented on README.md
>  ### Databricks Dispatch Configuration
Since we added this to the pre-req section can we remove it from the README

2022-05-05 20:55 UTC, fivetran-joemarkiewicz commented on README.md
> +    salesforce__<default_source_table_name>_identifier: your_table_name
Can we actually make this its own section within the README? A user doesn't **need** to configure this, but they may need to configure the database and schema variables.

2022-05-06 01:16 UTC, merged